create table
  public.fantasy_leagues (
    fantasy_league_id bigint generated by default as identity not null,
    fantasy_league_name character varying null,
    created_at timestamp with time zone null default now(),
    constraint fantasy_leagues_pkey primary key (fantasy_league_id)
  ) tablespace pg_default;

  create table
  public.users (
    user_id bigint generated by default as identity not null,
    user_name character varying null,
    is_admin boolean null,
    created_at timestamp with time zone null default now(),
    constraint users_pkey primary key (user_id)
  ) tablespace pg_default;

  create table
  public.fantasy_teams (
    fantasy_team_id bigint generated by default as identity not null,
    fantasy_team_name character varying null,
    created_at timestamp with time zone null default now(),
    user_id bigint null,
    fantasy_league_id bigint null,
    constraint fantasy_teams_pkey primary key (fantasy_team_id),
    constraint fantasy_teams_fantasy_league_id_fkey foreign key (fantasy_league_id) references fantasy_leagues (fantasy_league_id),
    constraint fantasy_teams_user_id_fkey foreign key (user_id) references users (user_id)
  ) tablespace pg_default;

  create table
  public.friends (
    user1_id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    user2_id bigint not null,
    constraint friends_pkey primary key (user1_id, user2_id)
  ) tablespace pg_default;

  create table
  public.positions (
    player_position character varying not null,
    created_at timestamp with time zone null default now(),
    constraint positions_pkey primary key (player_position)
  ) tablespace pg_default;

create table
  public.games (
    game_id bigint generated by default as identity not null,
    player_id bigint not null,
    num_goals bigint null,
    num_assists bigint null,
    num_passes bigint null,
    num_shots_on_goal bigint null,
    num_turnovers bigint null,
    created_at timestamp with time zone null default now(),
    constraint games_pkey primary key (game_id, player_id)
  ) tablespace pg_default;

  create table
  public.player_fantasy_team (
    player_id bigint generated by default as identity not null,
    fantasy_team_id bigint not null,
    constraint player_fantasy_team_pkey primary key (player_id, fantasy_team_id),
    constraint player_fantasy_team_fantasy_team_id_fkey foreign key (fantasy_team_id) references fantasy_teams (fantasy_team_id),
    constraint player_fantasy_team_player_id_fkey foreign key (player_id) references players (player_id)
  ) tablespace pg_default;

  create table
  public.players (
    player_id bigint generated by default as identity not null,
    player_name character varying null,
    irl_team_name character varying null,
    created_at timestamp with time zone null default now(),
    player_position character varying null,
    constraint players_pkey primary key (player_id),
    constraint players_player_position_fkey foreign key (player_position) references positions (player_position)
  ) tablespace pg_default;
